{
    "name": "Engel 사출 생산 관리",
    "version": "18.0.1.0.0",
    "summary": "Engel 사출기 연동 및 생산 데이터 관리 (Euromap 63 / Go Middleware)",
    "category": "Manufacturing",
    "license": "LGPL-3",
    "author": "DevSanx",
    "depends": [
        "base",
        "mail",
        "mrp",
        "stock",
        "hr",
        "iatf_document_control",
        "iatf_mold",
        "iatf_traceability",
        "iatf_process_inspection",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/car_model_views.xml",
        "views/defect_type_views.xml",
        "views/injection_serial_views.xml",
        "views/mrp_production_views.xml",
        "views/machine_status_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
