{
    "name": "IATF 작업환경 관리",
    "version": "18.0.1.2.0",
    "summary": "작업환경·5S 점검 + 범용 점검 일지 + 안전관리(위험성평가·아차사고)",
    "category": "Quality",
    "license": "LGPL-3",
    "author": "DevSanx",
    "depends": ["base", "mail", "hr", "mrp", "iatf_document_control", "iatf_equipment"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/work_environment_views.xml",
        "views/environment_check_views.xml",
        "views/check_sheet_views.xml",
        "views/check_record_views.xml",
        "views/safety_assessment_views.xml",
        "views/safety_incident_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
