{
    "name": "사출 생산계획 자동화",
    "version": "18.0.1.0.0",
    "summary": "Oracle 수요 연동 + BOM 전개 + 사출기 스케줄링 + MO 자동 생성",
    "category": "Manufacturing",
    "license": "LGPL-3",
    "author": "DevSanx",
    "depends": [
        "production_planning",
        "mail",
        "mrp",
        "stock",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "data/cron.xml",
        "data/default_config.xml",
        "views/mold_planning_views.xml",
        "views/planning_config_views.xml",
        "views/machine_mold_views.xml",
        "views/machine_availability_views.xml",
        "views/demand_views.xml",
        "views/planning_run_views.xml",
        "views/planning_line_views.xml",
        "views/planning_daily_summary_views.xml",
        "views/product_planning_views.xml",
        "wizards/generate_mo_wizard_views.xml",
        "wizards/import_demand_wizard_views.xml",
        "wizards/generate_demo_wizard_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
}
