{
    "name": "IATF Control Plan",
    "summary": "IATF 16949 §8.5.1.1 — Control Plan management (Prototype / Pre-Launch / Production)",
    "version": "18.0.1.0.0",
    "category": "Quality",
    "license": "LGPL-3",
    "author": "DevSanx",
    "depends": ["base", "mail", "mrp", "iatf_document_control", "iatf_fmea", "iatf_equipment", "iatf_approval"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/sequence.xml",
        "views/control_plan_views.xml",
        "views/mrp_workcenter_views.xml",
        "views/mrp_production_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": False,
}
