{
    "name": "IATF Quality Dashboard",
    "summary": "Central IATF 16949 dashboard with KPIs, cross-links, reports, and Excel import",
    "version": "18.0.1.0.0",
    "category": "Quality",
    "license": "LGPL-3",
    "author": "DevSanx",
    "depends": [
        "base", "mail", "web",
        "iatf_document_control",
        "iatf_nonconformity",
        "iatf_traceability",
        "iatf_apqp",
        "iatf_fmea",
        "iatf_control_plan",
        "iatf_ppap",
        "iatf_spc",
        "iatf_msa",
        "iatf_audit",
        "iatf_supplier_quality",
        "iatf_training",
        "iatf_calibration",
        "iatf_customer_complaint",
        "iatf_management_review",
        "iatf_contingency",
        "iatf_risk",
        "iatf_incoming_inspection",
        "iatf_process_inspection",
        "iatf_quality_objective",
        "iatf_change_management",
        "iatf_csr",
        "iatf_layout_inspection",
    ],
    "data": [
        "security/ir.model.access.csv",
        "data/paperformat.xml",
        "report/report_8d.xml",
        "report/report_8d_template.xml",
        "report/report_fmea.xml",
        "report/report_fmea_template.xml",
        "report/report_control_plan.xml",
        "report/report_control_plan_template.xml",
        "wizard/excel_import_views.xml",
        "views/dashboard_views.xml",
        "views/menu.xml",
    ],
    "installable": True,
    "application": True,
}
